/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "FreeRTOS_trace.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TraceEvent, TraceEvent, AUTO)


PB_BIND(TaskPriorityEvent, TaskPriorityEvent, AUTO)


PB_BIND(TaskCreatedEvent, TaskCreatedEvent, AUTO)


PB_BIND(NameEvent, NameEvent, AUTO)


PB_BIND(QueueCreatedEvent, QueueCreatedEvent, AUTO)


PB_BIND(StreamBufferCreatedEvent, StreamBufferCreatedEvent, AUTO)


PB_BIND(StreamBufferTransferEvent, StreamBufferTransferEvent, AUTO)




