_default:
    just --list

# Re-generate encoder/decoder code, compile and execute C unit tests.
test:
    rm -rf build
    mkdir -p build
    cmake -B build -DCMAKE_GENERATOR="Unix Makefiles"
    make -C build -j 4
    python run_tests.py -t 0.5 -j 4 build/bin/
