import json

evts = []
with open("dump", "r") as infile:
    for line in infile.readlines():
        evts.append(json.loads(line))

# Events are generated by the scheduler and are not guaranteed to be at a
# constant idx/ts. We iterate over the trace and extract information we want to
# check:

# Validate task/resource registration and metadata:
task_names = {}
queue_names = {}
queue_kinds = {}
evtmarker_names = {}
valmarker_names = {}
idle_task_id = None
timer_task_id = None
task_evtmarker_names = {}
task_valmarker_names = {}

for evt in evts:
    if "FreeRTOSMetadata" in evt:
        kind, val = next(iter(evt["FreeRTOSMetadata"].items()))
        if kind == "TaskName":
            task_names[val["task_id"]] = val["name"]
        elif kind == "QueueName":
            queue_names[val["queue_id"]] = val["name"]
        elif kind == "QueueKind":
            queue_kinds[val["queue_id"]] = val["kind"]
        elif kind == "TaskIsIdleTask":
            idle_task_id = val["task_id"]
        elif kind == "TaskIsTimerTask":
            timer_task_id = val["task_id"]
        elif kind == "TaskEvtmarkerName":
            task_evtmarker_names[(
                val["task_id"], val["evtmarker_id"])] = val["name"]
        elif kind == "TaskValmarkerName":
            task_valmarker_names[(
                val["task_id"], val["valmarker_id"])] = val["name"]
        continue

    if "BaseMetadata" in evt:
        kind, val = next(iter(evt["BaseMetadata"].items()))
        if kind == "EvtmarkerName":
            evtmarker_names[val["evtmarker_id"]] = val["name"]
        elif kind == "ValmarkerName":
            valmarker_names[val["valmarker_id"]] = val["name"]
        continue

assert idle_task_id is not None
assert timer_task_id is not None

print("task_names:", task_names)
print("queue_names:", queue_names)
print("queue_kinds:", queue_kinds)
print("evtmarker_names:", evtmarker_names)
print("valmarker_names:", valmarker_names)
print("task_evtmarker_names:", task_evtmarker_names)
print("task_valmarker_names:", task_valmarker_names)
print("idle_task_id:", idle_task_id)
print("timer_task_id:", timer_task_id)

assert task_names[1] == "mytask1"
assert task_names[2] == "mytask2"
assert task_names[3] == "mytask3"
assert task_names[idle_task_id] == "IDLE"
assert task_names[timer_task_id] == "Tmr Svc"

assert queue_kinds[1] == "FrqkMutex"
assert queue_names[1] == "mymutex1"

assert queue_kinds[2] == "FrqkRecursiveMutex"
assert queue_names[2] == "recmutex"

assert queue_kinds[3] == "FrqkQueue"
assert queue_names[3] == "my_q1"

assert evtmarker_names[1] == "MyEvts"
assert valmarker_names[1] == "MyVals"

assert task_evtmarker_names[(1, 0)] == "T1Evts"
assert task_valmarker_names[(1, 0)] == "T1Val"

# All tasks/queues created at runtime were seen (idle + timer service task
# are created lazily by the kernel once the scheduler starts) and actually run
# at least once:
task_created_ids = set()
queue_created_ids = set()
task_switched_in_ids = set()
for evt in evts:
    if "FreeRTOS" in evt:
        kind, val = next(iter(evt["FreeRTOS"]["kind"].items()))
        if kind == "TaskCreated":
            task_created_ids.add(val["task_id"])
        elif kind == "QueueCreated":
            queue_created_ids.add(val["queue_id"])
        elif kind == "TaskSwitchedIn":
            task_switched_in_ids.add(val["task_id"])
        continue
print("task_created_ids:", task_created_ids)
print("queue_created_ids:", queue_created_ids)
print("task_switched_in_ids:", task_switched_in_ids)
assert task_created_ids == {idle_task_id, timer_task_id}
assert queue_created_ids == {4}  # timer service command queue
assert task_switched_in_ids == {1, 2, 3, idle_task_id, timer_task_id}

# All queues are actually used at one point:
queue_send_ids = set()
queue_receive_ids = set()
for evt in evts:
    if "FreeRTOS" in evt:
        kind, val = next(iter(evt["FreeRTOS"]["kind"].items()))
        if kind == "QueueSend":
            queue_send_ids.add(val["queue_id"])
        elif kind == "QueueReceive":
            queue_receive_ids.add(val["queue_id"])
        continue
print("queue_send_ids:", queue_send_ids)
print("queue_receive_ids:", queue_receive_ids)
assert queue_send_ids == {1, 2, 3}
assert queue_receive_ids == {1, 2, 3}

# Markers are used, and start/ends don't underflow:
global_evtmarker_stack = []
global_evtmarker_used = set()  # evtmarker_ids seen
task_evtmarker_stack = []
task_evtmarker_used = set()  # evtmarker_ids seen
global_valmarker_used = set()  # valmarker_ids seen
task_valmarker_used = set()  # valmarker_ids seen

for evt in evts:
    if "FreeRTOS" in evt:
        kind, val = next(iter(evt["FreeRTOS"]["kind"].items()))
        if kind == "TaskEvtmarker":
            task_evtmarker_used.add(val["evtmarker_id"])
        elif kind == "TaskEvtmarkerBegin":
            task_evtmarker_stack.append(val["evtmarker_id"])
            task_evtmarker_used.add(val["evtmarker_id"])
        elif kind == "TaskEvtmarkerEnd":
            assert len(task_evtmarker_stack) > 0
            assert task_evtmarker_stack.pop() == val["evtmarker_id"]
        elif kind == "TaskValmarker":
            task_valmarker_used.add(val["valmarker_id"])
        continue
    if "Base" in evt:
        kind, val = next(iter(evt["Base"]["kind"].items()))
        if kind == "Evtmarker":
            global_evtmarker_used.add(val["evtmarker_id"])
        elif kind == "EvtmarkerBegin":
            global_evtmarker_stack.append(val["evtmarker_id"])
            global_evtmarker_used.add(val["evtmarker_id"])
        elif kind == "EvtmarkerEnd":
            assert len(global_evtmarker_stack) > 0
            assert global_evtmarker_stack.pop() == val["evtmarker_id"]
        elif kind == "Valmarker":
            global_valmarker_used.add(val["valmarker_id"])
        continue

print("task_evtmarker_used:", task_evtmarker_used)
print("global_evtmarker_used:", global_evtmarker_used)
print("task_valmarker_used:", task_valmarker_used)
print("global_valmarker_used:", global_valmarker_used)

assert task_evtmarker_used == {0}  # T1Evts (task_evtmarker_names[(0, 0)])
assert global_evtmarker_used == {1}  # MyEvts (evtmarker_names[1])
assert task_valmarker_used == {0}  # T1Val (task_valmarker_names[(0, 0)])
assert global_valmarker_used == {1}  # MyVals (valmarker_names[1])

print("ok!")
