name: ci-tband

on:
  push:
    branches: ["main"]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tband-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install just
        run:  sudo apt-get install just

      - name: Run
        working-directory: ${{github.workspace}}
        run: just unit_tests

  tband-baremetal-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install just
        run:  sudo apt-get install just

      - name: Install protoc
        run:  sudo apt-get install protobuf-compiler

      - name: Run
        working-directory: ${{github.workspace}}
        run: just baremetal_integration_tests
