name: ci-web

on:
  push:
    branches: ["main"]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: "wasm32-unknown-unknown"
          components: "clippy, rustfmt"

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install mdbook
        run: |
          mkdir ~/bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory="$HOME/bin"

      - name: Build documentation
        working-directory: ${{github.workspace}}/docs
        run: ~/bin/mdbook build

      - name: Build wasm bindings
        working-directory: ${{github.workspace}}/web/tband-wasm
        run: wasm-pack build

      - name: Run rust tests
        working-directory: ${{github.workspace}}/web/tband-wasm
        run: cargo test --all

      - name: Run clippy
        working-directory: ${{github.workspace}}/web/tband-wasm
        run: cargo clippy -- -D warnings

      - name: Check rust format
        working-directory: ${{github.workspace}}/web/tband-wasm
        run: cargo fmt -- --check

      - name: Setup node env
        working-directory: ${{github.workspace}}/web/website
        run: npm install

      - name: Check website format
        working-directory: ${{github.workspace}}/web/website
        run: npm run format:check

      - name: Build website
        working-directory: ${{github.workspace}}/web/website
        run: npm run build
